/* ============================================================
   MULTIPLICÓPOLIS v1 · Tablas de multiplicar
   GitHub Pages + Apps Script + Google Sheets
   ============================================================ */
const DEFAULT_BACKEND_URL = "https://script.google.com/macros/s/AKfycbwb6KWTNcDfl0z9w0Je5lMpxyREFHWW8YOLAEEjSCL_CXy_NEEgNONVzES22S5Wnr281A/exec";
const TEACHER_PIN = "45612378";
const APP = "multiplicopolis";
const TABLES = Array.from({length:12},(_,i)=>i+1);
const FACTORS = Array.from({length:12},(_,i)=>i+1);
const GROUPS_DEFAULT = ["3.ºA","3.ºB","4.ºA","4.ºB","5.ºA","5.ºB","6.ºA","6.ºB"];
const AVATARS = ["🦊","🐼","🦉","🐸","🐯","🐵","🦁","🐰","🐲","🦄","🚀","⭐"];
const RANKS = [
  {xp:0,name:"Aprendiz de Producto",icon:"🌱"},{xp:200,name:"Explorador de Tablas",icon:"🧭"},{xp:500,name:"Guardián del Cálculo",icon:"🛡️"},{xp:950,name:"Mago Multiplicador",icon:"🧙"},{xp:1500,name:"Leyenda de Multiplicópolis",icon:"🏆"}
];
const MODES = [
  ["normal","Resultado directo"],["reverse","Factor perdido"],["choice","Elige respuesta"],["truefalse","Verdadero o falso"],["speed","Reto rápido"]
];
const WORLDS = [
  {id:1, name:"Barrio de los Dobles", emoji:"🏘️", class:"w1", tables:[1,2,5]},
  {id:2, name:"Bosque de los Saltos", emoji:"🌳", class:"w2", tables:[3,4,6]},
  {id:3, name:"Volcán de los Retos", emoji:"🌋", class:"w3", tables:[7,8,9]},
  {id:4, name:"Torre Maestra", emoji:"🗼", class:"w4", tables:[10,11,12]}
];
const LEVELS = [];
WORLDS.forEach(w=>w.tables.forEach(t=>LEVELS.push({id:LEVELS.length+1,world:w.id,table:t,name:`Tabla del ${t}`,emoji:t<=5?"⚡":"💥"})));

const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const uid = () => Math.random().toString(36).slice(2,10)+Date.now().toString(36).slice(-4);
const today = () => new Date().toISOString().slice(0,10);
const weekKey = () => { const d=new Date(); const onejan=new Date(d.getFullYear(),0,1); return `${d.getFullYear()}-S${Math.ceil((((d-onejan)/86400000)+onejan.getDay()+1)/7)}`; };
const norm = s => String(s||"").trim().toLowerCase();
const shuffle = a => a.map(v=>[Math.random(),v]).sort((x,y)=>x[0]-y[0]).map(x=>x[1]);
const pick = a => a[Math.floor(Math.random()*a.length)];

let students = load("multiplicopolis-students", []);
let groups = load("multiplicopolis-groups", GROUPS_DEFAULT);
let settings = load("multiplicopolis-settings", { backendUrl: DEFAULT_BACKEND_URL, classCode:"Multiplicópolis Aula", accessible:false, quiet:false });
let missions = load("multiplicopolis-missions", {});
let exams = load("multiplicopolis-exams", []);
let grades = load("multiplicopolis-grades", []);
let queue = load("multiplicopolis-sync-queue", []);
let current = null;
let teacherUnlocked = sessionStorage.getItem("multiplicopolis-teacher") === "1";
let game = null;

function load(k, fallback){ try{return JSON.parse(localStorage.getItem(k)) ?? fallback}catch{return fallback} }
function save(k,v){ localStorage.setItem(k,JSON.stringify(v)); }
function saveAll(){ save("multiplicopolis-students",students); save("multiplicopolis-groups",groups); save("multiplicopolis-settings",settings); save("multiplicopolis-missions",missions); save("multiplicopolis-exams",exams); save("multiplicopolis-grades",grades); save("multiplicopolis-sync-queue",queue); }
function studentBase(name, group, pw){ return {id:uid(), name:name.trim(), group, password:pw.trim(), avatar:pick(AVATARS), xp:0, attempts:[], mistakes:{}, mastery:{}, levels:{}, bestStreak:0, days:{last:null,count:0}, createdAt:new Date().toISOString(), examsDone:{}}; }
function rankFor(xp){ return [...RANKS].reverse().find(r=>xp>=r.xp) || RANKS[0]; }
function activeStudent(){ return students.find(s=>s.id===current); }
function selectedValues(sel){ return [...sel.selectedOptions].map(o=>Number(o.value)||o.value); }
function fillSelect(sel, arr, all=false){ sel.innerHTML = all?`<option value="all">Todos</option>`:""; arr.forEach(v=>sel.insertAdjacentHTML("beforeend",`<option value="${v}">${v}</option>`)); }
function fillGroups(){ ["#loginGroupFilter","#newStudentGroup","#missionGroup","#examGroup"].forEach(id=>fillSelect($(id), groups, id==="#loginGroupFilter")); ["#trainTables","#missionTables","#examTables"].forEach(id=>fillSelect($(id), TABLES)); ["#studyTable","#printTable"].forEach(id=>fillSelect($(id), TABLES)); $("#trainMode").innerHTML = MODES.map(m=>`<option value="${m[0]}">${m[1]}</option>`).join(""); }

function init(){ fillGroups(); bind(); applySettings(); renderLogin(); syncPullConfig(false); }
function bind(){
  $("#addStudentBtn").onclick=addStudent; $("#newStudentName").addEventListener("keydown",e=>{if(e.key==="Enter")addStudent()}); $("#loginGroupFilter").onchange=renderLogin; $("#teacherLoginBtn").onclick=()=>{ if(requestTeacher()) showApp("teacher"); };
  $$(".tab").forEach(b=>b.onclick=()=>showApp(b.dataset.view)); $("#switchStudentBtn").onclick=logout;
  $("#startTrainBtn").onclick=()=>startGame({source:"train"}); $("#studyTable").onchange=renderStudy; $("#studyView").onchange=renderStudy; $("#practiceMistakes").onclick=()=>startGame({source:"mistakes"});
  $("#forceSyncBtn").onclick=()=>syncQueue(true); $("#syncAllBtn").onclick=()=>syncQueue(true); $("#exportCsvBtn").onclick=exportProgress; $("#exportGradesBtn").onclick=exportGrades; $("#lockTeacherBtn").onclick=lockTeacher;
  $$(".teacher-nav").forEach(b=>b.onclick=()=>showTeacherPanel(b.dataset.panel)); $("#saveMissionBtn").onclick=saveMission; $("#clearMissionBtn").onclick=clearMission; $("#createExamBtn").onclick=createExam; $("#addGroupBtn").onclick=addGroup;
  $("#saveBackendBtn").onclick=saveSettings; $("#testBackendBtn").onclick=testBackend; $("#publishConfigBtn").onclick=publishConfig; $("#pullConfigBtn").onclick=()=>syncPullConfig(true); $("#accessibleToggle").onchange=e=>{settings.accessible=e.target.checked;saveAll();applySettings()}; $("#quietToggle").onchange=e=>{settings.quiet=e.target.checked;saveAll();applySettings()}; $("#makeWorksheetBtn").onclick=makeWorksheet;
}
function applySettings(){ document.body.classList.toggle("accessible",!!settings.accessible); document.body.classList.toggle("quiet",!!settings.quiet); $("#accessibleToggle").checked=!!settings.accessible; $("#quietToggle").checked=!!settings.quiet; $("#backendUrlInput").value=settings.backendUrl||""; $("#classCodeInput").value=settings.classCode||""; }

function renderLogin(){
  fillGroups(); const filter=$("#loginGroupFilter").value||"all"; const list = students.filter(s=>filter==="all"||s.group===filter);
  $("#studentGrid").innerHTML = list.length? list.map(s=>{const r=rankFor(s.xp); return `<button class="student-card" data-id="${s.id}"><span class="sc-avatar">${s.avatar}</span><strong>${esc(s.name)}</strong><small>${esc(s.group)}</small><span class="sc-rank">${r.icon} ${r.name}</span></button>`}).join("") : `<div class="callout">Aún no hay perfiles en este grupo.</div>`;
  $$(".student-card").forEach(b=>b.onclick=()=>loginStudent(b.dataset.id)); $("#loginSyncState").textContent = settings.backendUrl?"☁️ Conectado a Sheets":"💾 Modo local";
}
function addStudent(){ const name=$("#newStudentName").value.trim(); const group=$("#newStudentGroup").value; const pw=$("#newStudentPw").value.trim(); if(!name||!pw)return alert("Escribe nombre y contraseña."); if(students.some(s=>norm(s.name)===norm(name)&&s.group===group))return alert("Ya existe un perfil con ese nombre en ese grupo."); const s=studentBase(name,group,pw); students.push(s); enqueue("student",s); saveAll(); $("#newStudentName").value=""; $("#newStudentPw").value=""; renderLogin(); }
function loginStudent(id){ const s=students.find(x=>x.id===id); if(!s)return; const pw=prompt(`Contraseña de ${s.name}`); if(pw===null)return; if(pw!==s.password)return alert("Contraseña incorrecta. Pregunta a tu maestro/a si no la recuerdas."); current=id; updateDay(s); saveAll(); $("#loginScreen").classList.add("hidden"); $("#appShell").classList.remove("hidden"); renderApp(); showApp("adventure"); syncQueue(false); }
function logout(){ current=null; $("#appShell").classList.add("hidden"); $("#loginScreen").classList.remove("hidden"); renderLogin(); }
function updateDay(s){ const t=today(); if(s.days.last!==t){ const y=new Date(); y.setDate(y.getDate()-1); s.days.count = s.days.last===y.toISOString().slice(0,10)?(s.days.count||0)+1:1; s.days.last=t; } }

function showApp(view){ if(view==="teacher"&&!teacherUnlocked){ if(!requestTeacher())return; } $$(".view").forEach(v=>v.classList.toggle("active",v.id===`view-${view}`)); $$(".tab").forEach(t=>t.classList.toggle("active",t.dataset.view===view)); if(view!=="teacher")renderApp(); else renderTeacher(); }
function requestTeacher(){ const c=prompt("Código de maestro/a"); if(c===null)return false; if(c===TEACHER_PIN){teacherUnlocked=true;sessionStorage.setItem("multiplicopolis-teacher","1");return true} alert("Código incorrecto"); return false; }
function lockTeacher(){ teacherUnlocked=false;sessionStorage.removeItem("multiplicopolis-teacher");showApp("adventure"); }
function showTeacherPanel(p){ $$(".teacher-nav").forEach(b=>b.classList.toggle("active",b.dataset.panel===p)); $$(".teacher-panel").forEach(x=>x.classList.toggle("active",x.id===`panel-${p}`)); renderTeacher(); }

function renderApp(){ const s=activeStudent(); if(!s)return; const r=rankFor(s.xp); $("#playerName").textContent=s.name; $("#groupLabel").textContent=`· ${s.group}`; $("#playerAvatar").textContent=s.avatar; $("#rankName").textContent=`${r.icon} ${r.name}`; $("#dailyStreak").textContent=`🔥 ${s.days.count||1} día${(s.days.count||1)>1?'s':''}`; $("#xpText").textContent=`${s.xp} XP`; $("#xpBar").style.width=`${Math.min(100,(s.xp%500)/5)}%`; renderMission(); renderWorldMap(); renderStudy(); renderReview(); renderProgress(); renderExamTab(); }
function renderMission(){ const s=activeStudent(); const m=missions[s.group]; const el=$("#missionBanner"); if(!m){el.classList.add("hidden");return} el.classList.remove("hidden"); el.innerHTML=`<div><strong>🎯 Misión de hoy: ${esc(m.title||"Entrena tablas")}</strong><br><small>Tablas: ${m.tables.join(", ")} · ${m.rounds} preguntas · XP doble</small></div><button class="secondary" id="startMissionBtn">Empezar misión</button>`; $("#startMissionBtn").onclick=()=>startGame({source:"mission", mission:m}); }
function renderWorldMap(){ const s=activeStudent(); const maxStars=LEVELS.length*3; const stars=Object.values(s.levels||{}).reduce((a,l)=>a+(l.stars||0),0); $("#starCount").textContent=`⭐ ${stars}/${maxStars}`; $("#worldMap").innerHTML=WORLDS.map(w=>{ const nodes=LEVELS.filter(l=>l.world===w.id); const prevOk = w.id===1 || LEVELS.filter(l=>l.world<w.id).every(l=>(s.levels[l.id]?.stars||0)>0); const locked=!prevOk; return `<article class="world ${w.class} ${locked?'locked':''}"><div class="world-head"><span class="world-emoji">${w.emoji}</span><div><h3>${w.name}</h3><small>Tablas ${w.tables.join(", ")}</small></div><span class="world-stars">⭐ ${nodes.reduce((a,l)=>a+(s.levels[l.id]?.stars||0),0)}/${nodes.length*3}</span></div><div class="level-path">${nodes.map(l=>levelNode(l,locked,s)).join("")}</div></article>`}).join(""); $$(".level-node:not(.locked)").forEach(b=>b.onclick=()=>startGame({source:"level", level:LEVELS.find(l=>l.id==b.dataset.id)})); }
function levelNode(l, worldLocked, s){ const prev = l.id===1 || (s.levels[l.id-1]?.stars||0)>0; const locked=worldLocked||!prev; const st=s.levels[l.id]?.stars||0; return `<button class="level-node ${locked?'locked':''} ${st===0&&!locked?'current':''}" data-id="${l.id}"><span class="em">${locked?'🔒':l.emoji}</span><strong>${l.table}×</strong><span class="stars">${'⭐'.repeat(st)}${'☆'.repeat(3-st)}</span></button>`; }
function renderStudy(){ const t=Number($("#studyTable").value||1), mode=$("#studyView").value; $("#tableStudy").innerHTML = FACTORS.map(f=>`<div class="mult-row"><span>${t} × ${f}</span><strong class="${mode==='hide'?'hidden-result':''}">${t*f}</strong>${mode==='groups'?`<small>${f} grupos de ${t}</small>`:""}</div>`).join(""); }
function renderReview(){ const s=activeStudent(); const entries=Object.entries(s.mistakes||{}).sort((a,b)=>b[1]-a[1]); $("#reviewCount").textContent=entries.length; $("#mistakeList").innerHTML= entries.length?entries.slice(0,20).map(([k,n])=>`<div class="mistake"><strong>${k.replace('x',' × ')}</strong> · ${n} fallo${n>1?'s':''}</div>`).join(""):`<div class="callout">No hay errores pendientes. ¡Buen trabajo!</div>`; }
function renderProgress(){ const s=activeStudent(); const stats=calcStats(s); $("#statXp").textContent=s.xp; $("#statAcc").textContent=`${stats.acc}%`; $("#statBest").textContent=s.bestStreak||0; $("#statSolved").textContent=stats.total; $("#masteryBars").innerHTML=TABLES.map(t=>{ const m=tableMastery(s,t); return `<div class="bar-line"><div class="bar-label"><span>Tabla del ${t}</span><span>${m}%</span></div><div class="bar"><span style="width:${m}%"></span></div></div>`}).join(""); renderPodium(); renderLog(); }
function renderPodium(){ const s=activeStudent(); const wk=weekKey(); const list=students.filter(x=>x.group===s.group).map(x=>({name:x.name,avatar:x.avatar,xp:x.attempts.filter(a=>a.week===wk).reduce((n,a)=>n+(a.xp||0),0)})).sort((a,b)=>b.xp-a.xp).slice(0,5); $("#podium").innerHTML=list.map((p,i)=>`<div class="podium-item"><span>${["🥇","🥈","🥉","⭐","⭐"][i]} ${p.avatar} ${esc(p.name)}</span><span>${p.xp} XP</span></div>`).join("")||"<p class='tiny'>Aún no hay actividad esta semana.</p>"; }
function renderLog(){ const s=activeStudent(); $("#activityLog").innerHTML=[...(s.attempts||[])].slice(-10).reverse().map(a=>`<div class="activity"><strong>${a.correct}/${a.total}</strong> · ${a.source} · ${a.tables?.join(', ')||''}<br><small>${new Date(a.at).toLocaleString()}</small></div>`).join("")||"<p class='tiny'>Todavía no hay actividad.</p>"; }
function renderExamTab(){ const s=activeStudent(); const available=exams.filter(e=>e.group===s.group && !s.examsDone[e.id]); $("#examTab").classList.toggle("hidden",available.length===0); $("#examList").innerHTML=available.length?available.map(e=>`<div class="exam-row"><strong>${esc(e.title)}</strong><br><small>Tablas ${e.tables.join(', ')} · ${e.n} preguntas</small><br><button class="primary small" data-exam="${e.id}">Hacer examen</button></div>`).join(""):`<div class="callout">No tienes exámenes pendientes.</div>`; $$('[data-exam]').forEach(b=>b.onclick=()=>startGame({source:"exam",exam:exams.find(e=>e.id===b.dataset.exam)})); }

function makeQuestion(tables, mode){ const a=pick(tables), b=pick(FACTORS), ans=a*b; if(mode==="reverse"){ const missing=Math.random()<.5?"a":"b"; return {mode, a,b,ans, prompt: missing==="a"?`? × ${b} = ${ans}`:`${a} × ? = ${ans}`, correct: missing==="a"?a:b}; } if(mode==="choice"){ const opts=shuffle([ans, ans+a, Math.max(0,ans-b), ans+10, ans-a]).filter((v,i,ar)=>ar.indexOf(v)===i).slice(0,4); return {mode,a,b,ans,prompt:`${a} × ${b}`, correct:ans, opts:shuffle(opts)}; } if(mode==="truefalse"){ const shown=Math.random()<.55?ans:ans+pick([-10,-5,-3,-2,2,3,5,10]); return {mode,a,b,ans,prompt:`${a} × ${b} = ${shown}`, correct:shown===ans, shown}; } return {mode:"normal",a,b,ans,prompt:`${a} × ${b}`,correct:ans}; }
function startGame(cfg){ const s=activeStudent(); if(!s && cfg.source!=="preview")return; let tables=[...selectedValues($("#trainTables"))].filter(Number); let rounds=Number($("#rounds").value)||10, mode=$("#trainMode").value||"normal"; let source=cfg.source; if(cfg.level){tables=[cfg.level.table];rounds=8;mode="normal"} if(cfg.mission){tables=cfg.mission.tables;rounds=Number(cfg.mission.rounds)||10;mode="normal"} if(cfg.source==="mistakes"){ const keys=Object.keys(s.mistakes||{}); if(!keys.length)return alert("No tienes errores pendientes."); tables=[...new Set(keys.map(k=>Number(k.split('x')[0])))]; rounds=Math.min(20,Math.max(8,keys.length)); mode="normal"; } if(cfg.exam){tables=cfg.exam.tables;rounds=cfg.exam.n;mode="mixed"} if(!tables.length)tables=TABLES; const qs=Array.from({length:rounds},()=>makeQuestion(tables, mode==="mixed"?pick(["normal","reverse","choice","truefalse"]):mode)); game={cfg,tables,rounds,mode,qs,i:0,correct:0,streak:0,best:0,answers:[],source}; document.body.classList.add("playing"); $("#gameOverlay").classList.remove("hidden"); renderQuestion(); }
function renderQuestion(){ const q=game.qs[game.i]; const pct=(game.i/game.rounds)*100; $("#gameOverlay").innerHTML=`<div class="game-frame"><div class="game-top"><button class="ghost small" id="closeGame">Salir</button><h3>${game.source==='exam'?'📝 Examen':game.source==='level'?'🗺️ Nivel':game.source==='mission'?'🎯 Misión':'⚡ Entrenamiento'}</h3><strong>${game.correct} ✅</strong></div><div class="hud"><span>${game.i+1}/${game.rounds}</span><div class="game-progress"><span style="width:${pct}%"></span></div><span>🔥 ${game.streak}</span></div><div id="qArea"></div><div id="feedback" class="feedback"></div></div>`; $("#closeGame").onclick=endGameEarly; const area=$("#qArea"); if(q.mode==="choice")area.innerHTML=`<p class="prompt">Elige el resultado</p><div class="question">${q.prompt}</div><div class="options">${q.opts.map(o=>`<button class="option" data-v="${o}">${o}</button>`).join("")}</div>`; else if(q.mode==="truefalse")area.innerHTML=`<p class="prompt">¿Es correcto?</p><div class="question">${q.prompt}</div><div class="options"><button class="option" data-v="true">Verdadero</button><button class="option" data-v="false">Falso</button></div>`; else area.innerHTML=`<p class="prompt">Resuelve</p><div class="question">${q.prompt}</div><div class="answer-row"><input id="answerInput" inputmode="numeric" autocomplete="off" autofocus><button id="checkBtn" class="primary">Comprobar</button></div>`; $$(".option").forEach(b=>b.onclick=()=>checkAnswer(b.dataset.v)); const inp=$("#answerInput"); if(inp){inp.focus(); $("#checkBtn").onclick=()=>checkAnswer(inp.value); inp.addEventListener("keydown",e=>{if(e.key==="Enter")checkAnswer(inp.value)});} }
function checkAnswer(v){ const q=game.qs[game.i]; let val = q.mode==="truefalse" ? (v==="true") : Number(v); const ok = val===q.correct; if(ok){ game.correct++; game.streak++; game.best=Math.max(game.best,game.streak); feedback("¡Correcto!",true); } else { game.streak=0; feedback(`Casi. Era ${q.correct===true?'verdadero':q.correct===false?'falso':q.correct}`,false); } game.answers.push({a:q.a,b:q.b,answer:val,correct:q.correct,ok}); if(q.mode==="choice"||q.mode==="truefalse"){ $$(".option").forEach(o=>{ const ov=q.mode==="truefalse"?(o.dataset.v==="true"):Number(o.dataset.v); o.classList.add(ov===q.correct?"correct":(ov===val?"wrong":"")); }); } setTimeout(()=>{ game.i++; if(game.i>=game.rounds)finishGame(); else renderQuestion(); }, ok?650:1050); }
function feedback(msg, ok){ const f=$("#feedback"); f.textContent=msg; f.className=`feedback ${ok?'good':'bad'}`; }
function endGameEarly(){ if(confirm("¿Salir del reto?")){document.body.classList.remove("playing");$("#gameOverlay").classList.add("hidden");} }
function finishGame(){ const s=activeStudent(); const total=game.rounds, correct=game.correct, acc=Math.round(correct/total*100); const isExam=game.source==="exam"; const xp = isExam?0:Math.max(5,correct*8*(game.source==="mission"?2:1)); const stars=acc>=90?3:acc>=70?2:acc>=50?1:0; if(s){ s.xp+=xp; s.bestStreak=Math.max(s.bestStreak||0,game.best); const attempt={id:uid(),app:APP,studentId:s.id,name:s.name,group:s.group,source:game.source,at:new Date().toISOString(),week:weekKey(),tables:game.tables,total,correct,acc,xp,answers:game.answers}; s.attempts.push(attempt); game.answers.forEach(a=>{ const key=`${a.a}x${a.b}`; if(a.ok){ if(s.mistakes[key]){s.mistakes[key]--; if(s.mistakes[key]<=0)delete s.mistakes[key];} } else s.mistakes[key]=(s.mistakes[key]||0)+1; }); game.tables.forEach(t=>updateMastery(s,t)); if(game.cfg.level){ const id=game.cfg.level.id; const old=s.levels[id]?.stars||0; s.levels[id]={stars:Math.max(old,stars),best:Math.max(s.levels[id]?.best||0,acc)}; } if(isExam){ const e=game.cfg.exam; const grade=Number((correct/total*10).toFixed(1)); const g={id:uid(),examId:e.id,title:e.title,studentId:s.id,name:s.name,group:s.group,at:new Date().toISOString(),tables:game.tables,total,correct,grade,answers:game.answers}; grades.push(g); s.examsDone[e.id]=true; enqueue("grade",g); } enqueue("attempt",attempt); saveAll(); }
  $("#gameOverlay").innerHTML=`<div class="game-frame end"><div class="emoji">${acc>=80?'🏆':acc>=50?'⭐':'💪'}</div><h2>${isExam?'Examen terminado':'Reto completado'}</h2>${isExam?`<div class="grade ${acc>=50?'ok':'bad'}">${(correct/total*10).toFixed(1)}</div>`:`<div class="question">${'⭐'.repeat(stars)}${'☆'.repeat(3-stars)}</div><p>+${xp} XP</p>`}<p>${correct}/${total} correctas · ${acc}%</p><button id="endOk" class="primary big">Continuar</button></div>`; $("#endOk").onclick=()=>{document.body.classList.remove("playing");$("#gameOverlay").classList.add("hidden");renderApp();}; syncQueue(false); }
function updateMastery(s,t){ const attempts=(s.attempts||[]).flatMap(a=>a.answers||[]).filter(x=>x.a===t||x.b===t).slice(-30); const acc=attempts.length?Math.round(attempts.filter(x=>x.ok).length/attempts.length*100):0; s.mastery[t]=acc; }
function tableMastery(s,t){ return s.mastery?.[t] || 0; }
function calcStats(s){ const total=(s.attempts||[]).reduce((n,a)=>n+a.total,0); const correct=(s.attempts||[]).reduce((n,a)=>n+a.correct,0); return {total,correct,acc:total?Math.round(correct/total*100):0}; }

function renderTeacher(){ fillGroups(); renderClassSummary(); renderMissions(); renderExamManage(); renderStudents(); }
function renderClassSummary(){ const rows=students.map(s=>{const st=calcStats(s);return {...s,stats:st}}); $("#classSummary").innerHTML=`<table class="table"><thead><tr><th>Alumno/a</th><th>Grupo</th><th>Clave</th><th>XP</th><th>Acierto</th><th>Errores</th></tr></thead><tbody>${rows.map(s=>`<tr><td>${s.avatar} ${esc(s.name)}</td><td>${esc(s.group)}</td><td><code>${esc(s.password||'')}</code></td><td>${s.xp}</td><td>${s.stats.acc}%</td><td>${Object.keys(s.mistakes||{}).length}</td></tr>`).join("")}</tbody></table>`; const weak=[]; students.forEach(s=>TABLES.forEach(t=>{if((s.mastery?.[t]||0)<50 && (s.attempts||[]).length>0)weak.push(`${s.name}: tabla ${t}`)})); $("#teacherRadar").innerHTML=weak.length?weak.slice(0,12).map(w=>`<div class="mistake">${esc(w)}</div>`).join(""):`<div class="callout">Sin alertas todavía.</div>`; }
function renderMissions(){ $("#missionList").innerHTML=Object.entries(missions).map(([g,m])=>`<div class="activity"><strong>${esc(g)}</strong>: ${esc(m.title)} · tablas ${m.tables.join(', ')}</div>`).join("")||"<p class='tiny'>Sin misiones guardadas.</p>"; }
function saveMission(){ const g=$("#missionGroup").value; const tables=selectedValues($("#missionTables")).filter(Number); missions[g]={title:$("#missionTitle").value.trim()||"Misión de tablas", tables:tables.length?tables:TABLES, rounds:Number($("#missionRounds").value)||10}; saveAll(); renderTeacher(); }
function clearMission(){ delete missions[$("#missionGroup").value]; saveAll(); renderTeacher(); }
function createExam(){ const tables=selectedValues($("#examTables")).filter(Number); const e={id:uid(),title:$("#examTitle").value.trim()||"Evaluación de tablas", group:$("#examGroup").value, tables:tables.length?tables:TABLES, n:Number($("#examN").value)||20, timer:$("#examTimer").checked, createdAt:new Date().toISOString()}; exams.push(e); saveAll(); renderTeacher(); }
function renderExamManage(){ $("#examManageList").innerHTML=exams.map(e=>`<div class="exam-row"><strong>${esc(e.title)}</strong> · ${esc(e.group)} · tablas ${e.tables.join(', ')}<br><small>Notas: ${grades.filter(g=>g.examId===e.id).length}</small></div>`).join("")||"<p class='tiny'>No hay evaluaciones.</p>"; }
function addGroup(){ const g=$("#newGroupName").value.trim(); if(!g)return; if(!groups.includes(g))groups.push(g); $("#newGroupName").value=""; saveAll(); fillGroups(); renderTeacher(); }
function renderStudents(){ const by=Object.groupBy?Object.groupBy(students,s=>s.group):students.reduce((a,s)=>((a[s.group]??=[]).push(s),a),{}); $("#groupStudentList").innerHTML=Object.entries(by).map(([g,arr])=>`<h3>${esc(g)}</h3>${arr.map(s=>`<div class="student-row">${s.avatar} <strong>${esc(s.name)}</strong> · clave: <code>${esc(s.password||'')}</code> · ${s.xp} XP</div>`).join("")}`).join("")||"<p class='tiny'>Sin alumnado.</p>"; }
function makeWorksheet(){ const t=Number($("#printTable").value||1); const qs=shuffle(FACTORS).map(f=>`${t} × ${f} = ______`); $("#worksheet").innerHTML=`<h2>Ficha · Tabla del ${t}</h2><p>Nombre: ____________________ Fecha: ____________</p>${qs.map(q=>`<p style="font-size:1.35rem">${q}</p>`).join("")}`; }

function saveSettings(){ settings.backendUrl=$("#backendUrlInput").value.trim(); settings.classCode=$("#classCodeInput").value.trim()||"Multiplicópolis Aula"; saveAll(); alert("Ajustes guardados"); }
function enqueue(type,payload){ queue.push({type,payload,app:APP,at:new Date().toISOString()}); saveAll(); }
async function post(payload){ if(!settings.backendUrl)throw new Error("Sin URL backend"); const body=JSON.stringify({app:APP,classCode:settings.classCode,...payload}); await fetch(settings.backendUrl,{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain;charset=utf-8"},body}); return true; }
async function syncQueue(manual){ if(!queue.length){ if(manual)alert("No hay datos pendientes."); return; } const copy=[...queue]; try{ await post({type:"batch",items:copy}); queue=[]; saveAll(); if(manual)alert("Sincronizado."); }catch(e){ if(manual)alert("No se pudo sincronizar. Queda en cola."); } }
async function testBackend(){ try{ await post({type:"ping",payload:{time:new Date().toISOString()}}); alert("Conexión enviada. Comprueba la hoja si quieres verificar registro."); }catch(e){ alert("No se pudo conectar."); } }
async function publishConfig(){ try{ await post({type:"config",payload:{missions,exams,groups,settings:{classCode:settings.classCode}}}); alert("Configuración publicada al aula."); }catch(e){ alert("No se pudo publicar."); } }
async function syncPullConfig(manual){ if(!settings.backendUrl)return; try{ const url=settings.backendUrl+`?app=${encodeURIComponent(APP)}&classCode=${encodeURIComponent(settings.classCode)}&type=config`; const r=await fetch(url); const data=await r.json(); if(data.ok&&data.config){ missions=data.config.missions||missions; exams=data.config.exams||exams; groups=data.config.groups||groups; saveAll(); fillGroups(); if(manual)alert("Configuración descargada."); } }catch(e){ if(manual)alert("No se pudo descargar configuración."); } }
function exportProgress(){ downloadCsv("multiplicopolis_progreso.csv", students.flatMap(s=>(s.attempts||[]).map(a=>({alumno:s.name,grupo:s.group,fecha:a.at,tablas:(a.tables||[]).join('|'),total:a.total,correctas:a.correct,acierto:a.acc,xp:a.xp,tipo:a.source})))); }
function exportGrades(){ downloadCsv("multiplicopolis_notas.csv", grades.map(g=>({alumno:g.name,grupo:g.group,examen:g.title,fecha:g.at,nota:g.grade,total:g.total,correctas:g.correct,tablas:g.tables.join('|')}))); }
function downloadCsv(name, rows){ if(!rows.length)return alert("No hay datos."); const keys=Object.keys(rows[0]); const csv=[keys.join(';'),...rows.map(r=>keys.map(k=>`"${String(r[k]??'').replaceAll('"','""')}"`).join(';'))].join('\n'); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})); a.download=name; a.click(); }
function esc(s){ return String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c])); }

init();
